### ISSUE TITLE
Titles localized

### ISSUE THREAD

**Issue by memnos** [adamgot/python-plexlibrary#36]
Hello,
is it possibile creating libraries with movie tiltles in a language different from english?
I'd like to use it with titles in Italian.
Tnx

**Comment by adamgot** [comment]
Just edit the library settings in Plex.

On 13 Jul 2018, at 10:43, memnos <notifications@github.com> wrote:

Hello,
is it possibile creating libraries with movie tiltles in a language
different from english?
I'd like to use it with titles in Italian.
Tnx

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adamgot/python-plexlibrary/issues/36>, or mute the
thread

**Comment by memnos** [comment]
I can edit library in plex into it, but for example if i use recipe per imdb top 250, titles are locked as a number is put before name so they don't change into italian even if i refresh db.

**Comment by petercris** [comment]
> I can edit library in plex into it, but for example if i use recipe per imdb top 250, titles are locked as a number is put before name so they don't change into italian even if i refresh db.

I just edited movies_imdb_top_250.yml line 25 (visible: yes) to no. I lost the number in the title, but when I refreshed the metadata, the titles changed to Spanish, in my case. I don't know if there's a better way.

**Comment by xfouloux** [comment]
I know issue is closed, but well even setting the library to another lang did not do the trick.
Titles are still in english, not in localized title, cause it is taken from trakt list i guess ?
Because then everything else is localized.
