### ISSUE TITLE
Created 0 Symlinks

### ISSUE THREAD

**Issue by Veepas** [adamgot/python-plexlibrary#42]
Hello there,

i was using the script which worked flawless as far as i can tell. But it says:

`Creating symlinks for 4 matching items in the library...
Created symlinks for 0 new items:
`

I do use unionfs if it has to do something about it ?

Please help me use this wonderful little piece of script :)

Greetings

**Comment by jacc1234** [comment]
I am having the same issue, using union-fs and docker for my PMS. Could it have something to do with the way the volumes used by docker don't match the paths used in the script?

**Comment by adamgot** [comment]
Hi,

Union-FS shouldn’t be the issue, but rather the writeable filesystem layers beneath. Make sure you’re trying to write to a file system that supports creating symlinks. 

Preferably just write to your local disk, no need to keep the links in the same place as the media files.

As for docker there should probably be a way to do it with shared volumes, but I haven’t tried.

**Comment by adamgot** [comment]
Hi,

Union-FS shouldn’t be the issue, but rather the writeable filesystem layers beneath. Make sure you’re trying to write to a file system that supports creating symlinks. 

Preferably just write to your local disk, no need to keep the links in the same place as the media files.

As for docker there should probably be a way to do it with shared volumes, but I haven’t tried.

**Comment by Veepas** [comment]
> I am having the same issue, using union-fs and docker for my PMS. Could it have something to do with the way the volumes used by docker don't match the paths used in the script?
> 
> Example:
> Docker Plex Moves Path = /moves -> System Path = /home/plex/media/moves
> 
> I would expect the symlinks to still get created and then possibly have to change the path in the plex app.
> 
> I have not tried to run the script from within the container but will give that a try tomorrow.

Did you manage to accomplish to change the docker image appropriate?

I am not quite sure what to do to get this script to work flawless

**Comment by themurderlator** [comment]
I seem to be having the same issue where there are 0 symlinks created and I believe it's because it's confused on how to create the symlinks.  Since my Plex server is connected to my NAS via UNC, it's impossible for `os.symlink(old_path, new_path)` to actually complete since that Python command won't work for UNC shares/paths.

This script is being ran from my NAS directly, so I've been going down a rabbit hole to figure out if it's possible to implement the way the Path Mapping works on [Plex_Autoscan](https://github.com/l3uddz/plex_autoscan).

This way Python-Plexlibrary would see /volume2/TV as \\fileserver\TV and it would create the symlinks correctly.
