### ISSUE TITLE
remove_from_library

### ISSUE THREAD

**Issue by Migz93** [adamgot/python-plexlibrary#53]
Hi,

I was just wondering if the option "remove_from_library:" removes the file or removes the symlink?
The info above the option isn't 100% clear, it says "Remove items that no longer exist in the source lists" but that doesn't explain if it means it'll remove the symlink or remove the underlying files themselves?

**Comment by adamgot** [comment]
It will only remove the symbolic link.

On 6 Apr 2019, at 17:42, Migz93 <notifications@github.com> wrote:

Hi,

I was just wondering if the option "remove_from_library:" removes the file
or removes the symlink?
The info above the option isn't 100% clear, it says "Remove items that no
longer exist in the source lists" but that doesn't explain if it means
it'll remove the symlink or remove the underlying files themselves?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adamgot/python-plexlibrary/issues/53>, or mute the
thread

**Comment by Migz93** [comment]
Thanks for the confirmation.
