### ISSUE TITLE
Support sharing playlists to other users

### ISSUE THREAD

**Issue by adamgot** [adamgot/python-plexlibrary#83]
I'm imagining some setting in the recipe to specify certain users (default server owner only?) and preferably also a flag to bypass that and add to all users.

Adding the playlist to other users should be relatively straight forward using this https://python-plexapi.readthedocs.io/en/latest/modules/playlist.html#plexapi.playlist.Playlist.copyToUser

Is there a way to delete/update another user's playlist? Overwrite?

I'm also not sure how you would get a list of all users.

**Comment by blacktwin** [comment]
There are 2 types of the TOKENs per account, user and server. You as the server admin have access to the server TOKENs that shared users use to connect to your server. With this you can modify somethings for them.

With plexapi:
```python
from plexapi.server import PlexServer
plex = PlexServer(PLEX_URL, PLEX_TOKEN)
account = plex.myPlexAccount()
users = account.users() # get all your plex users
for user in users:
    user_server = PlexServer(PLEX_URL, user_acct.get_token(plex.machineIdentifier))
    user_playlist = user_server.playlist('That Playlist')
```

With the `user_server` you can do what you would with your `plex` object. Obviously you have some restrictions because you're a user and not the admin but most of the methods will return something. `user_playlist` being one of them.  

Here is an [example](https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py) of how I use this method to share playlists.

**Comment by nwithan8** [comment]
Finished the functionality. Share to specific users or share to all indicated in recipe, but adding the CLI flag for override now. Pull request coming soon.
